#!/bin/sh
set -eu

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
source_dir="$root/source"
output_dir="$root/generated"
check=false

"$root/scripts/validate-external.sh" "$source_dir/external"

if [ "${1:-}" = "--check" ]; then
    check=true
fi

work_dir=$(mktemp -d)
trap 'rm -rf "$work_dir"' EXIT HUP INT TERM

render_adapter() {
    destination=$1
    title=$2
    mkdir -p "$(dirname "$destination")"
    {
        printf '<!-- Generated by scripts/generate.sh. Do not edit. -->\n\n'
        printf '# %s\n\n' "$title"
        cat "$source_dir/baseline/BASELINE.md"
        printf '\n'
        cat "$source_dir/reviews/INDEX.md"
        printf '\n'
        for review in "$source_dir"/reviews/*.md; do
            [ "$(basename "$review")" = "INDEX.md" ] && continue
            printf '\n'
            cat "$review"
        done
    } > "$destination"
}

render_adapter "$work_dir/claude-code/CLAUDE.md" "Claude Code instructions"
render_adapter "$work_dir/codex/AGENTS.md" "Codex instructions"
render_adapter "$work_dir/github-copilot/ai-guardrails.instructions.md" "GitHub Copilot instructions"
render_adapter "$work_dir/cursor/ai-guardrails.mdc" "Cursor instructions"
render_adapter "$work_dir/gemini/GEMINI.md" "Gemini instructions"

for review in "$source_dir"/reviews/*.md; do
    name=$(basename "$review" .md)
    [ "$name" = "INDEX" ] && continue
    mkdir -p "$work_dir/claude-code/skills/$name"
    {
        printf '%s\n' '---'
        printf 'name: %s\n' "$name"
        printf '%s\n\n' '---'
        cat "$source_dir/baseline/BASELINE.md"
        printf '\n'
        cat "$source_dir/reviews/INDEX.md"
        printf '\n'
        cat "$review"
    } > "$work_dir/claude-code/skills/$name/SKILL.md"
done

for external_dir in "$source_dir"/external/*; do
    [ -d "$external_dir" ] || continue
    name=$(basename "$external_dir")
    mkdir -p "$work_dir/external-skills/$name"
    {
        printf '%s\n' '---'
        printf 'name: external-%s\n' "$name"
        printf 'description: Reviewed external skill content managed by ai-guardrails.\n'
        printf '%s\n\n' '---'
        cat "$source_dir/baseline/BASELINE.md"
        printf '\n'
        cat "$external_dir/CONTENT.md"
    } > "$work_dir/external-skills/$name/SKILL.md"
done

if "$check"; then
    diff -ru "$output_dir" "$work_dir"
else
    rm -rf "$output_dir"
    mv "$work_dir" "$output_dir"
    trap - EXIT HUP INT TERM
fi
